spring.application.name=vanconhung

spring.datasource.url=jdbc:postgresql://localhost:5432/vanconhung
spring.datasource.username=vanconhung
spring.datasource.password=vanconhung
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=g2rUkLTTaPN4/LcdVcXmgUlORfccE/ZNqjhAJ4ImcymHVKrmWlYK6QvqiCLQrBMxMl3hjg3JcjYGsBzJKQpCMg==
app.jwt.expiration-ms=86400000

app.cors.allowed-origins=http://localhost:5173

app.seed.teacher.username=admin
app.seed.teacher.password=admin123
