services:
  postgres:
    image: postgres:16-alpine
    container_name: vanconhung-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vanconhung
      POSTGRES_USER: vanconhung
      POSTGRES_PASSWORD: vanconhung
    ports:
      - "5432:5432"
    volumes:
      - vanconhung-postgres-data:/var/lib/postgresql/data

volumes:
  vanconhung-postgres-data:
